#ifndef BAXTER_HPP
#define BAXTER_HPP
#include<eigen3/Eigen/Core>
namespace baxter
{
    using Eigen::VectorXd;
    using Eigen::MatrixXd;
    static const double L = 278e-3;
    static const double h = 64e-3;
    static const double H = 1104e-3;
    static const double L0 = 270.35e-3;
    static const double L1 = 69e-3;
    static const double L2 = 364.35e-3;
    static const double L3 = 69e-3;
    static const double L4 = 374.29e-3;
    static const double L5 = 10e-3;
    static const double L6 = 368.3e-3;
    void o_W0(const VectorXd& q, VectorXd& out);
    void o_BR(const VectorXd& q, VectorXd& out);
    void o_0(const VectorXd& q, VectorXd& out);
    void o_1(const VectorXd& q, VectorXd& out);
    void o_2(const VectorXd& q, VectorXd& out);
    void o_3(const VectorXd& q, VectorXd& out);
    void o_4(const VectorXd& q, VectorXd& out);
    void o_5(const VectorXd& q, VectorXd& out);
    void o_6(const VectorXd& q, VectorXd& out);
    void o_ee(const VectorXd& q, VectorXd& out);
    void rx_W0(const VectorXd& q, VectorXd& out);
    void rx_BR(const VectorXd& q, VectorXd& out);
    void rx_0(const VectorXd& q, VectorXd& out);
    void rx_1(const VectorXd& q, VectorXd& out);
    void rx_2(const VectorXd& q, VectorXd& out);
    void rx_3(const VectorXd& q, VectorXd& out);
    void rx_4(const VectorXd& q, VectorXd& out);
    void rx_5(const VectorXd& q, VectorXd& out);
    void rx_6(const VectorXd& q, VectorXd& out);
    void rx_ee(const VectorXd& q, VectorXd& out);
    void ry_W0(const VectorXd& q, VectorXd& out);
    void ry_BR(const VectorXd& q, VectorXd& out);
    void ry_0(const VectorXd& q, VectorXd& out);
    void ry_1(const VectorXd& q, VectorXd& out);
    void ry_2(const VectorXd& q, VectorXd& out);
    void ry_3(const VectorXd& q, VectorXd& out);
    void ry_4(const VectorXd& q, VectorXd& out);
    void ry_5(const VectorXd& q, VectorXd& out);
    void ry_6(const VectorXd& q, VectorXd& out);
    void ry_ee(const VectorXd& q, VectorXd& out);
    void rz_W0(const VectorXd& q, VectorXd& out);
    void rz_BR(const VectorXd& q, VectorXd& out);
    void rz_0(const VectorXd& q, VectorXd& out);
    void rz_1(const VectorXd& q, VectorXd& out);
    void rz_2(const VectorXd& q, VectorXd& out);
    void rz_3(const VectorXd& q, VectorXd& out);
    void rz_4(const VectorXd& q, VectorXd& out);
    void rz_5(const VectorXd& q, VectorXd& out);
    void rz_6(const VectorXd& q, VectorXd& out);
    void rz_ee(const VectorXd& q, VectorXd& out);
    void jo_W0(const VectorXd& q, MatrixXd& out);
    void jo_BR(const VectorXd& q, MatrixXd& out);
    void jo_0(const VectorXd& q, MatrixXd& out);
    void jo_1(const VectorXd& q, MatrixXd& out);
    void jo_2(const VectorXd& q, MatrixXd& out);
    void jo_3(const VectorXd& q, MatrixXd& out);
    void jo_4(const VectorXd& q, MatrixXd& out);
    void jo_5(const VectorXd& q, MatrixXd& out);
    void jo_6(const VectorXd& q, MatrixXd& out);
    void jo_ee(const VectorXd& q, MatrixXd& out);
    void jrx_W0(const VectorXd& q, MatrixXd& out);
    void jrx_BR(const VectorXd& q, MatrixXd& out);
    void jrx_0(const VectorXd& q, MatrixXd& out);
    void jrx_1(const VectorXd& q, MatrixXd& out);
    void jrx_2(const VectorXd& q, MatrixXd& out);
    void jrx_3(const VectorXd& q, MatrixXd& out);
    void jrx_4(const VectorXd& q, MatrixXd& out);
    void jrx_5(const VectorXd& q, MatrixXd& out);
    void jrx_6(const VectorXd& q, MatrixXd& out);
    void jrx_ee(const VectorXd& q, MatrixXd& out);
    void jry_W0(const VectorXd& q, MatrixXd& out);
    void jry_BR(const VectorXd& q, MatrixXd& out);
    void jry_0(const VectorXd& q, MatrixXd& out);
    void jry_1(const VectorXd& q, MatrixXd& out);
    void jry_2(const VectorXd& q, MatrixXd& out);
    void jry_3(const VectorXd& q, MatrixXd& out);
    void jry_4(const VectorXd& q, MatrixXd& out);
    void jry_5(const VectorXd& q, MatrixXd& out);
    void jry_6(const VectorXd& q, MatrixXd& out);
    void jry_ee(const VectorXd& q, MatrixXd& out);
    void jrz_W0(const VectorXd& q, MatrixXd& out);
    void jrz_BR(const VectorXd& q, MatrixXd& out);
    void jrz_0(const VectorXd& q, MatrixXd& out);
    void jrz_1(const VectorXd& q, MatrixXd& out);
    void jrz_2(const VectorXd& q, MatrixXd& out);
    void jrz_3(const VectorXd& q, MatrixXd& out);
    void jrz_4(const VectorXd& q, MatrixXd& out);
    void jrz_5(const VectorXd& q, MatrixXd& out);
    void jrz_6(const VectorXd& q, MatrixXd& out);
    void jrz_ee(const VectorXd& q, MatrixXd& out);
    void jo_W0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_BR_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_1_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_2_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_3_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_4_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_5_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_6_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jo_ee_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_W0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_BR_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_1_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_2_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_3_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_4_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_5_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_6_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrx_ee_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_W0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_BR_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_1_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_2_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_3_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_4_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_5_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_6_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jry_ee_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_W0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_BR_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_0_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_1_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_2_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_3_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_4_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_5_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_6_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
    void jrz_ee_dot(const VectorXd& q, const VectorXd& q_dot, MatrixXd& out);
};
#endif